// Generated by gencpp from file thorlabs_linear_actuator/thorlab_responses.msg
// DO NOT EDIT!


#ifndef THORLABS_LINEAR_ACTUATOR_MESSAGE_THORLAB_RESPONSES_H
#define THORLABS_LINEAR_ACTUATOR_MESSAGE_THORLAB_RESPONSES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thorlabs_linear_actuator
{
template <class ContainerAllocator>
struct thorlab_responses_
{
  typedef thorlab_responses_<ContainerAllocator> Type;

  thorlab_responses_()
    : response()  {
    }
  thorlab_responses_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> const> ConstPtr;

}; // struct thorlab_responses_

typedef ::thorlabs_linear_actuator::thorlab_responses_<std::allocator<void> > thorlab_responses;

typedef boost::shared_ptr< ::thorlabs_linear_actuator::thorlab_responses > thorlab_responsesPtr;
typedef boost::shared_ptr< ::thorlabs_linear_actuator::thorlab_responses const> thorlab_responsesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator1> & lhs, const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator1> & lhs, const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace thorlabs_linear_actuator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thorlabs_linear_actuator/thorlab_responses";
  }

  static const char* value(const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct thorlab_responses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thorlabs_linear_actuator::thorlab_responses_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THORLABS_LINEAR_ACTUATOR_MESSAGE_THORLAB_RESPONSES_H
