// Generated by gencpp from file universal_robots/position_command.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_ROBOTS_MESSAGE_POSITION_COMMAND_H
#define UNIVERSAL_ROBOTS_MESSAGE_POSITION_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace universal_robots
{
template <class ContainerAllocator>
struct position_command_
{
  typedef position_command_<ContainerAllocator> Type;

  position_command_()
    : p()  {
      p.assign(0.0);
  }
  position_command_(const ContainerAllocator& _alloc)
    : p()  {
  (void)_alloc;
      p.assign(0.0);
  }



   typedef boost::array<double, 3>  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::universal_robots::position_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::universal_robots::position_command_<ContainerAllocator> const> ConstPtr;

}; // struct position_command_

typedef ::universal_robots::position_command_<std::allocator<void> > position_command;

typedef boost::shared_ptr< ::universal_robots::position_command > position_commandPtr;
typedef boost::shared_ptr< ::universal_robots::position_command const> position_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::universal_robots::position_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::universal_robots::position_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::universal_robots::position_command_<ContainerAllocator1> & lhs, const ::universal_robots::position_command_<ContainerAllocator2> & rhs)
{
  return lhs.p == rhs.p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::universal_robots::position_command_<ContainerAllocator1> & lhs, const ::universal_robots::position_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace universal_robots

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::universal_robots::position_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_robots::position_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::universal_robots::position_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::universal_robots::position_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_robots::position_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_robots::position_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::universal_robots::position_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1abbaca176899a0863a2922ff57df9ac";
  }

  static const char* value(const ::universal_robots::position_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1abbaca176899a08ULL;
  static const uint64_t static_value2 = 0x63a2922ff57df9acULL;
};

template<class ContainerAllocator>
struct DataType< ::universal_robots::position_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "universal_robots/position_command";
  }

  static const char* value(const ::universal_robots::position_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::universal_robots::position_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] p\n"
;
  }

  static const char* value(const ::universal_robots::position_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::universal_robots::position_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::universal_robots::position_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::universal_robots::position_command_<ContainerAllocator>& v)
  {
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.p[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIVERSAL_ROBOTS_MESSAGE_POSITION_COMMAND_H
