// Generated by gencpp from file ros_falcon/falconSetPoint.msg
// DO NOT EDIT!


#ifndef ROS_FALCON_MESSAGE_FALCONSETPOINT_H
#define ROS_FALCON_MESSAGE_FALCONSETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_falcon
{
template <class ContainerAllocator>
struct falconSetPoint_
{
  typedef falconSetPoint_<ContainerAllocator> Type;

  falconSetPoint_()
    : X(0.0)
    , Y(0.0)
    , Z(0.0)  {
    }
  falconSetPoint_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , Z(0.0)  {
  (void)_alloc;
    }



   typedef double _X_type;
  _X_type X;

   typedef double _Y_type;
  _Y_type Y;

   typedef double _Z_type;
  _Z_type Z;





  typedef boost::shared_ptr< ::ros_falcon::falconSetPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_falcon::falconSetPoint_<ContainerAllocator> const> ConstPtr;

}; // struct falconSetPoint_

typedef ::ros_falcon::falconSetPoint_<std::allocator<void> > falconSetPoint;

typedef boost::shared_ptr< ::ros_falcon::falconSetPoint > falconSetPointPtr;
typedef boost::shared_ptr< ::ros_falcon::falconSetPoint const> falconSetPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_falcon::falconSetPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_falcon::falconSetPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_falcon::falconSetPoint_<ContainerAllocator1> & lhs, const ::ros_falcon::falconSetPoint_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X &&
    lhs.Y == rhs.Y &&
    lhs.Z == rhs.Z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_falcon::falconSetPoint_<ContainerAllocator1> & lhs, const ::ros_falcon::falconSetPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_falcon

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_falcon::falconSetPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_falcon::falconSetPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_falcon::falconSetPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8219583d7802cc50be3e9ab911877ba5";
  }

  static const char* value(const ::ros_falcon::falconSetPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8219583d7802cc50ULL;
  static const uint64_t static_value2 = 0xbe3e9ab911877ba5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_falcon/falconSetPoint";
  }

  static const char* value(const ::ros_falcon::falconSetPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 X\n"
"float64 Y\n"
"float64 Z\n"
;
  }

  static const char* value(const ::ros_falcon::falconSetPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct falconSetPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_falcon::falconSetPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_falcon::falconSetPoint_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<double>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<double>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<double>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_FALCON_MESSAGE_FALCONSETPOINT_H
